import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientLayout from "./clientLayout";
import Header from "./_components/header/page";
import Sidebar from "./_components/sidebar/page";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link href="/style.css" rel="stylesheet" />
      </head>
      <body>
        {/* <>
          <div className="app-layout-collapsible-side flex flex-auto flex-col">
            <div className="flex flex-auto min-w-0">
              {" "}
              <Sidebar />
              <div className="flex flex-col flex-auto min-h-screen min-w-0 relative w-full">
                <Header />
                {children}
              </div>
            </div>
          </div>
        </> */}
        <ToastContainer />
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
